MODEL:
  NAME: 'ViT-B-16'
  PRETRAIN_PATH: "pretrained/ViT-B-32.pt"   # 可换为clip的路径或huggingface路径
  BACKBONE:
    TYPE: "clip_vit_base_patch32"
    WITH_NORM: True
  META_ARCHITECTURE: "clip_reid_rga"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  STRIDE_SIZE: [16, 16]
  FP16_ENABLED: True
  RGA:
    REGION_NAMES: ["head", "upper body", "lower body", "foot"]
    GAMMA: 5.0
    DIS_THRESHOLD: 0.85
    MEMORY_MOMENTUM: 0.2
    NUM_REGIONS: 4

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  DO_FLIP: True
  FLIP_PROB: 0.5
  PADDING: 10

DATALOADER:
  SAMPLER: "softmax_triplet"
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  # OPT: "Adam"
  # MAX_EPOCHS: 120
  # BASE_LR: 0.00035
  # WEIGHT_DECAY: 5e-4
  # BIAS_LR_FACTOR: 2
  # IMS_PER_BATCH: 64
  # WARMUP_ITERS: 10
  # STEPS: [40, 70]
  # GAMMA: 0.1
  # CHECKPOINT_PERIOD: 10
  SEED: 42
  # LARGE_FC_LR: False
  IMS_PER_BATCH: 8
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.000005
  WARMUP_METHOD: 'linear'
  WARMUP_ITERS: 10
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY:  0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  LARGE_FC_LR: False
  MAX_EPOCHS: 60
  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 50
  EVAL_PERIOD: 60
  BIAS_LR_FACTOR: 2
  
  STEPS: [30, 50]
  GAMMA: 0.1


  STAGE1:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY:  1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 120
    CHECKPOINT_PERIOD: 120
    LOG_PERIOD: 50
    WARMUP_EPOCHS: 5
  
  STAGE2:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.000005
    WARMUP_METHOD: 'linear'
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY:  0.0001
    WEIGHT_DECAY_BIAS: 0.0001
    LARGE_FC_LR: False
    MAX_EPOCHS: 60
    CHECKPOINT_PERIOD: 60
    LOG_PERIOD: 50
    EVAL_PERIOD: 60
    BIAS_LR_FACTOR: 2
    
    STEPS: [30, 50]
    GAMMA: 0.1

TEST:
  FEAT_NORM: True
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 64
  RE_RANKING: False

DATASETS:
  NAMES: ("market1501")
  ROOT_DIR: ('/home/sunnylab')
OUTPUT_DIR: '/home/sunnylab/RGANet-CLIP/outputs'
